
 export const courses = [
    {
      id: 1,
      title: 'ReactJS Crash Course 2023',
      instructor: 'Traversy Media',
      description: 'Learn ReactJS basics including components, state, and props.',
      duration: '2 months',
      level: 'Beginner',
      playlistId: 'PLSsAz5wf2lkK_ekd0J__44KG6QoXetZza', // Updated playlist ID
      enrolled: 50,
      videoCount: 6,
      thumbnail: 'https://img.youtube.com/vi/MHn66JJH5zs/sddefault.jpg',
      category: 'Web Development',
      subcategory: 'Frontend',
      language: 'English',
    },
    {
      id: 2,
      title: 'JavaScript Full Course',
      instructor: 'freeCodeCamp.org',
      description: 'Comprehensive JavaScript course covering basics to advanced concepts.',
      duration: '8 weeks',
      level: 'Beginner to Advanced',
      playlistId: 'PLWKjhJtqVAbljeMjAXDUCMhLBgk5jJIMW', // Updated playlist ID
      enrolled: 85,
      videoCount: 38,
      thumbnail: 'https://img.youtube.com/vi/PkZNo7MFNFg/sddefault.jpg',
      category: 'Web Development',
      subcategory: 'Programming Languages',
      language: 'English',
    },
    {
      id: 3,
      title: 'Python for Beginners',
      instructor: 'Programming with Mosh',
      description: 'Master Python basics with hands-on projects.',
      duration: '5 weeks',
      level: 'Beginner',
      playlistId: 'PLTjRvDozrdlxEIuOBZkMAK5uiqp8rHUax', // Updated playlist ID
      enrolled: 75,
      videoCount: 11,
      thumbnail: 'https://img.youtube.com/vi/_uQrJ0TkZlc/sddefault.jpg',
      category: 'Programming',
      subcategory: 'Backend',
      language: 'English',
    },
    {
      id: 4,
      title: 'Data Structures and Algorithms',
      instructor: 'Abdul Bari',
      description: 'Learn DSA concepts with in-depth explanations and examples.',
      duration: '6 weeks',
      level: 'Intermediate',
      playlistId: 'PLdo5W4Nhv31aBrJeG9Z6zphEb9gOT1r8R', // Updated playlist ID
      enrolled: 60,
      videoCount: 41,
      thumbnail: 'https://img.youtube.com/vi/RBSGKlAvoiM/sddefault.jpg',
      category: 'Computer Science',
      subcategory: 'Algorithms',
      language: 'English',
    },
    {
      id: 5,
      title: 'Machine Learning with Python',
      instructor: 'freeCodeCamp.org',
      description: 'Dive into machine learning concepts and build practical projects.',
      duration: '6 weeks',
      level: 'Beginner to Intermediate',
      playlistId: 'PLDxCaNaYJ-DR1A5gyZtPSjTtJzP5eOgK2', // Updated playlist ID
      enrolled: 55,
      videoCount: 27,
      thumbnail: 'https://img.youtube.com/vi/GwIo3gDZCVQ/sddefault.jpg',
      category: 'Data Science',
      subcategory: 'Machine Learning',
      language: 'English',
    },
    {
      id: 6,
      title: 'Full-Stack Web Development Bootcamp',
      instructor: 'The Net Ninja',
      description: 'Comprehensive course covering HTML, CSS, JavaScript, React, and Node.js.',
      duration: '12 weeks',
      level: 'Beginner to Advanced',
      playlistId: 'PL4cUxeGkcC9jLYyp2uCJb0l2_Ci1b-aSc', // Updated playlist ID
      enrolled: 120,
      videoCount: 45,
      thumbnail: 'https://img.youtube.com/vi/pkMUI8ENXts/sddefault.jpg',
      category: 'Web Development',
      subcategory: 'Full Stack',
      language: 'English',
    },
    {
      id: 7,
      title: 'Cybersecurity Fundamentals',
      instructor: 'NetworkChuck',
      description: 'Learn the basics of cybersecurity, including hacking and security tools.',
      duration: '4 weeks',
      level: 'Beginner',
      playlistId: 'PLIFyRwBY_4bRL5d_PW1dJZCbyvSNZC9BI', // Updated playlist ID
      enrolled: 45,
      videoCount: 8,
      thumbnail: 'https://img.youtube.com/vi/HhfrA1_qpZ0/sddefault.jpg',
      category: 'Cybersecurity',
      subcategory: 'Network Security',
      language: 'English',
    },
    {
      id: 8,
      title: 'AWS Certified Solutions Architect',
      instructor: 'freeCodeCamp.org',
      description: 'Prepare for AWS certification with detailed explanations and projects.',
      duration: '10 weeks',
      level: 'Intermediate to Advanced',
      playlistId: 'PLWKjhJtqVAblcmCsKDbDAsfZA2JZvV8iI', // Updated playlist ID
      enrolled: 35,
      videoCount: 22,
      thumbnail: 'https://img.youtube.com/vi/IuFZGEuqV9s/sddefault.jpg',
      category: 'Cloud Computing',
      subcategory: 'Infrastructure',
      language: 'English',
    },
    {
      id: 9,
      title: 'Advanced CSS and Sass',
      instructor: 'freeCodeCamp.org',
      description: 'Master advanced CSS and Sass to create responsive and modern web designs.',
      duration: '5 weeks',
      level: 'Intermediate',
      playlistId: 'PL69e9jTxnCoJ_-UUBppOb2XlFDPr5tvri', // New course with playlist ID
      enrolled: 65,
      videoCount: 12,
      thumbnail: 'https://img.youtube.com/vi/1Rs2ND1ryYc/sddefault.jpg',
      category: 'Web Development',
      subcategory: 'Frontend',
      language: 'English',
    },{
      id: 11,
      title: 'Learn TypeScript for Beginners',
      instructor: 'Academind',
      description: 'Introduction to TypeScript and how it enhances JavaScript development.',
      duration: '3 weeks',
      level: 'Beginner',
      playlistId: 'PL55RiY5tL51qimLHksqfDT9Efx2NDEe9s', // Updated playlist ID
      enrolled: 40,
      videoCount: 15,
      thumbnail: 'https://img.youtube.com/vi/BwuLxPH8IDs/sddefault.jpg',
      category: 'Programming',
      subcategory: 'Languages',
      language: 'English',
    },
    {
      id: 12,
      title: 'Introduction to Linux',
      instructor: 'The Linux Foundation',
      description: 'Learn Linux basics and essential commands.',
      duration: '4 weeks',
      level: 'Beginner',
      playlistId: 'PL6gx4Cwl9DGBwibXFtPtflztSNPGuIB_d', // Updated playlist ID
      enrolled: 30,
      videoCount: 10,
      thumbnail: 'https://img.youtube.com/vi/0m4x11D1MyA/sddefault.jpg',
      category: 'Operating Systems',
      subcategory: 'Linux',
      language: 'English',
    },
    {
      id: 13,
      title: 'SQL Full Course',
      instructor: 'Simplilearn',
      description: 'Master SQL queries, database design, and data analysis.',
      duration: '6 weeks',
      level: 'Beginner to Intermediate',
      playlistId: 'PLAA9E0FD28900FA76', // Updated playlist ID
      enrolled: 80,
      videoCount: 20,
      thumbnail: 'https://img.youtube.com/vi/HhHG90w5XxA/sddefault.jpg',
      category: 'Data Science',
      subcategory: 'Databases',
      language: 'English',
    },
    {
      id: 14,
      title: 'Android App Development for Beginners',
      instructor: 'CodeWithHarry',
      description: 'Learn how to build Android applications using Java and XML.',
      duration: '8 weeks',
      level: 'Beginner',
      playlistId: 'PLu0W_9lII9ah7DDtYtflgwMwpT3xmjXY9', // Updated playlist ID
      enrolled: 90,
      videoCount: 35,
      thumbnail: 'https://img.youtube.com/vi/mXjZQX3UzOs/sddefault.jpg',
      category: 'Mobile Development',
      subcategory: 'Android',
      language: 'English',
    },
    {
      id: 15,
      title: 'Artificial Intelligence Basics',
      instructor: 'Stanford Online',
      description: 'Introduction to AI principles and applications.',
      duration: '7 weeks',
      level: 'Beginner',
      playlistId: 'PLGgtICjoZ8aGpHZi4SK9pR65xGs9gc55E', // Updated playlist ID
      enrolled: 55,
      videoCount: 10,
      thumbnail: 'https://img.youtube.com/vi/nFZFbF8RBFs/sddefault.jpg',
      category: 'Artificial Intelligence',
      subcategory: 'Basics',
      language: 'English',
    }
  ];